server:
  port: 8080
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
      lastName: Demo
    login:
      enabled: true
      user-id: demo
    filter:
      create: All tasks
    generic-properties:
      properties:
        initializeTelemetry: false

spring:
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE
    username: demo
    password: secret
  h2:
    console:
      enabled: true